### ISSUE TITLE
Refactor speakers block to use srcset

### ISSUE THREAD

**Issue by cjyabraham** [LF-Engineering/lfevents#419]
Images are currently being served as background images in css but these can't take advantage of responsive images served using srcset.  Speaker images [on this page](https://events.linuxfoundation.org/kubecon-cloudnativecon-north-america/), for example, use [this file](https://events.linuxfoundation.org/wp-content/uploads/profile-18-personal-crop-10MB-scaled.jpg) which is 845KB.

So, rewrite the block to implement the images using srcset.

**Comment by rodmeurer** [comment]
Done @cjyabraham 
https://github.com/LF-Engineering/lfevents/tree/fz-419

**Comment by cjyabraham** [comment]
This doesn't look correct on mobile view.  See how it looks on [your version](https://pr-425-lfeventsci.pantheonsite.io/open-networking-edge-summit-north-america/program/program-committee/) vs the [live version](https://events.linuxfoundation.org/open-networking-edge-summit-north-america/program/program-committee/).  Your version doesn't fill the borders of the surrounding box correctly and the corners are sharp:
<img width="524" alt="Screen Shot 2020-01-18 at 3 46 02 PM" src="https://user-images.githubusercontent.com/463160/72661157-affe0b80-3a09-11ea-868e-4fb97f08eb95.png">

Here is the live version:
<img width="397" alt="Screen Shot 2020-01-18 at 3 47 07 PM" src="https://user-images.githubusercontent.com/463160/72661174-d0c66100-3a09-11ea-8953-5270e5bb99c8.png">

**Comment by cjyabraham** [comment]
@thetwopct suggests adding object fit cover and width: 100% to the image in the block to fix the issue:
![image](https://user-images.githubusercontent.com/463160/72734876-462e5f00-3bcd-11ea-8548-f76d617b4a90.png)

**Comment by rodmeurer** [comment]
Fixed @cjyabraham !

**Comment by cjyabraham** [comment]
It looks like there's still a problem with the height as in some cases it doesn't fill the full container.  See [this page](https://pr-425-lfeventsci.pantheonsite.io/open-networking-edge-summit-north-america/program/program-committee/) compared with the [live site](https://events.linuxfoundation.org/open-networking-edge-summit-north-america/program/program-committee/).  In your version we still have this gap:
<img width="222" alt="Screen Shot 2020-01-21 at 11 44 26 AM" src="https://user-images.githubusercontent.com/463160/72776087-70226880-3c43-11ea-8627-72c5b02a8498.png">

**Comment by cjyabraham** [comment]
Also, please do #428 on the same branch and I'll deploy together.

**Comment by rodmeurer** [comment]
@cjyabraham Adjusted. We implemented your suggestion for the add_image_size function, in addition to setting the height to 100%. We believe that now it will solve the problem.

**Comment by cjyabraham** [comment]
Looks good.  Can you also add another image size for 310px as on certain screens the images are almost that size.  so `add_image_size( 'profile-310', 310, 310, array( 'center', 'center') );`

**Comment by rodmeurer** [comment]
Updated with the new image size @cjyabraham

**Comment by cjyabraham** [comment]
Looks good.  I'll close this issue now but will wait for #428 before deploying.
